### ISSUE TITLE
Transparency issues

### ISSUE THREAD

**Issue by tmo26** [dwp-forge/batchedit#22]
1) After updating to 2018-08-18 the settings popup is transparent, which makes it hard to read:
![grafik](https://user-images.githubusercontent.com/12309103/45047109-6a40dd00-b078-11e8-843f-faff9bebb6e7.png)

2) Tooltip is transparent
![grafik](https://user-images.githubusercontent.com/12309103/45047315-ffdc6c80-b078-11e8-9bb0-df327dcaa458.png)

Can you please make it non-transparent, in order to improve readability?

**Comment by dwp-forge** [comment]
Could you share your template, so I could reproduce?

**Comment by tmo26** [comment]
Template: https://openwrt.org/_media/wiki/owrt_wiki_tpl.tar.gz

**Comment by dwp-forge** [comment]
You have a semi-transparent background color in your template. But the background opacity is set to 0.8 and though it doesn't look great, I would say that for the most part it looks satisfactory:

![image](https://user-images.githubusercontent.com/11460562/45258797-4e666f80-b3c7-11e8-8319-4fdb1c3f256a.png)

I suspect that in your case the problem may be related to the browser you use. I don't want to sound rude, but do you happen use Internet Explorer in 2018? If that's your thing (no judging), then I will have to disappoint you. Dropping IE support was a conscious choice I had to make.

You could try to make things look a bit better by adding the following into your [userstyle.css](https://www.dokuwiki.org/devel:css#user_styles):
``` css
body .ui-widget.ui-widget-content.be-tooltip,
body #batchedit .be-match,
body #batchedit #be-extoptions {
    background-color: #eee;
}

body #batchedit #be-totalstats div {
    background-color: #dde4e7;
}
```
