### ISSUE TITLE
text color with bootstrap3

### ISSUE THREAD

**Issue by suedunham** [dwp-forge/batchedit#36]
I'm having trouble with the way text appears in the matches when using a dark theme, such as darkly, with the bootstrap3 template. In this situation, the white body text is shown against a white background for many of the be- classes like the match text, page name, etc..

I'm guessing there's a way I could modify conf/userstyle.css to control this, but I'm a css noob and haven't found the right way to do this yet. Please let me know how, if this is that case.

**Comment by dwp-forge** [comment]
CSS prioritizes rules based on their specificity. A selector that more specifically identifies an element wins and its rules override any rules from less specific selectors. There are number of [rules](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) to determine the specificity, but in simple cases it boils down to the number of elements in selector -- a longer selector wins.

Now to the practical part. All BatchEdit selectors start with `#batchedit` that selects `div` element with `id="batchedit"`. That div is nested in other elements, so you can make more specific rule by mentioning those elements as well. For example, content part of the page is wrapped in a `div` element with `id="dokuwiki__content"`, so you can add in `userstyle.css` the following:

``` css
#dokuwiki__content #batchedit .be-match .be-preview {
    background-color: #f00;
}

```
With this rule you should see matched text on red background.

You may need to purge DW cache.

**Comment by suedunham** [comment]
Thanks for the help. I've gotten something workable by changing not the background but the text with the following for the Darkly theme:
```css
body.darkly #dokuwiki__content #batchedit .be-match, 
body.darkly #dokuwiki__content #batchedit #be-totalstats .control-label {
	color: black;
}
```

Perhaps that could be written more elegantly. The white-on-white changed to this:

![darkly_batchedit_500](https://user-images.githubusercontent.com/42522840/86833190-33b6bd80-c067-11ea-9d03-89dd0ad42919.jpg)

I could see the effect of changing the background, but that change was just for the text itself as the yellow highlights appear. How would one change the entire white or light gray spaces around it? The box that each block of text is in, for instance. I'm afraid I don't know the proper terms for those elements.

**Comment by dwp-forge** [comment]
Try to set background on `body.darkly #dokuwiki__content #batchedit .be-match table`.

**Comment by suedunham** [comment]
Excellent, thanks. I've gotten much of it done to my liking with this:
```css
/* batchedit pages with bootstrap3 template themes */
body.darkly #dokuwiki__content #batchedit .be-match {
    background: #222222;
    table {
        background: #303030;
        .be-arrow polyline {
            stroke: #ffffff;
        }
    }
    .be-preview {
        background-color: #8c8c00; 
    }
}
```
![darkly_batchedit_closer_500](https://user-images.githubusercontent.com/42522840/86936713-5f3fb380-c10c-11ea-937d-1d751c5844f6.jpg)

Some things still elude me though. I can get at blue on orange bit with this, but nothing I've tried touches the whitespace around it.
```css
/* problem area -- need to change whole white box */
body.darkly #dokuwiki__content #batchedit #be-totalstats {
    color: blue;
    .be-apply {
        background-color: orange;
    }
}
```
Then, though the `be-preview` class is highlighted more darkly, the results of applied changes are still in their original colors. Trying to get at the page source resubmits the input, so I can't see what those classes are called.

**Comment by dwp-forge** [comment]
It's `body.darkly #dokuwiki__content #batchedit #be-totalstats div`.

**Comment by suedunham** [comment]
Well, that looks like lesson one to someone learning this properly. Sigh. Here's what I finished up with. Thanks.
```css
/* BatchEdit result pages with bootstrap3 template theme (darkly)  */
body.darkly #dokuwiki__content #batchedit {
    /* Background around Search results (apply all) checkbox */
    #be-totalstats div {
        background: #222222;
    }
    /* Each match: outer background, inner background, arrow */
    .be-match {
        background: #222222;
        table {
            background: #303030;
            .be-arrow polyline {
                stroke: #ffffff;
            }
        }
        /* Text highlights for matches and replacements */
        .be-preview, .be-replaced {
            background-color: #f39c12;  /* warning color */
        }
        .be-applied {
            background-color: #00bc8c;  /* success color */
        }
    }
}
```
